function getRandomGreeting() {
  var greetings = [
    "Beep boop! Are you a robot?",
    "Did you know I have a discord server?",
    "How many sides does a circle have?",
    "You can read btw",
    "Made you look!",
    "Redbull gives you wings...",
    "Since 2020!",
    "As seen on TV!",
    "Made by Riggaunited",
    "Cold as ice!",
    "Made in the US!",
    "Made by 3kh0!",
    "Reload the page NOW!",
    "Downloading your passwords...",
    "Running 3kh0.exe",
    "WARNING: You may lose braincells if you proceed!",
    "Do you bite your ice cream?",
    "#Creamynation",
    "Fortnite is cringe",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Got to go fast!",
    "My iPad passcode is 563543 btw",
    "Sponsered by RAID SHADOW LEGENDS!",
    "Sponsored by Honey!",
    "Sponsored by 3kh0!",
    "Nelson is cute",
    "Liam is a bozo",
    "Powered by 128 Gigs of RAM!",
    "Powered by 16MB of RAM!",
    "Free Solomon!",
    "You're a jerk!",
    "Free david",
    "3kh0.net is here!",
    "what the dog doin?",
    "I'm gonna pop some tags",
    "Shoutout to @z0sopp!",
    "thx stackoverflow!",
    "are you a gaemer?",
    "It is time to get funky!",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "Hollyland is a FREAK",
    "Shoutout to Piplup!",
    "Shoutout to 3kh0!",
    "Woo! /g/",
    "youtube.com/watch?v=dQw4w9WgXcQ",
    "youtube.com/@3kh0",
    "Please stop posting furry images.",
    "Is this the United Airlines costumer service center?",
    "Cancel Jacob Alexander Johnson.",
    "bottem text",
    "Why do they call it oven if you oven the cold food of out hot eat the food",
    "No Thang allowed",
    "Your toes will be pulled tonight",
    "i do love buying birth certificates from the black market! - Piplup",
    "HUnt down Bryant.",
    "Zo is a furry!",
    "i wanted free vbucks :(",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for Vbucks",
    "Why does the discord server exist",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "Riggaunited never dies!",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "That proves you are unusual",
    "What's my age again?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "Thang? Cringe!",
    "Passing the gas is pretty fun",
    "Mission failed, we will get them next time",
    "JOSEPH INCOMING!",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
